#!/usr/bin/env python3
# Copyright 2026, Sirius Contributors.
# Licensed under the Apache License, Version 2.0 (the "License").
# See the LICENSE file at the repo root for the full text.
"""Import the pinned BenchBox TPC-Havoc SQL into the Catch2 query inventory.

Requires PyYAML only when regenerating; the C++ tests need no network or YAML
parser. Use --source-dir for an offline directory containing q01.yaml..q22.yaml.
"""

from __future__ import annotations

import argparse
import json
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.request import urlopen

import yaml

REVISION = "0a5b88a35946bb0bd86181ae41e7595d8d54d9fb"
SOURCE = "benchbox/core/tpchavoc/variant_sets"
OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "test/cpp/integration/data/tpch_havoc/queries.inc"
)


def read_query(number: int, source_dir: Path | None) -> list[dict]:
    filename = f"q{number:02}.yaml"
    if source_dir is not None:
        content = (source_dir / filename).read_text(encoding="utf-8")
    else:
        url = (
            f"https://raw.githubusercontent.com/BenchBox-dev/BenchBox/"
            f"{REVISION}/{SOURCE}/{filename}"
        )
        with urlopen(url, timeout=30) as response:
            content = response.read().decode("utf-8")
    variants = yaml.safe_load(content)["variants"]
    if len(variants) != 10 or sorted(v["id"] for v in variants) != list(range(1, 11)):
        raise ValueError(f"{filename}: expected exactly variant IDs 1 through 10")
    for variant in variants:
        if not isinstance(variant["description"], str):
            raise ValueError(f"{filename}: missing variant description")
        sql = variant["sql"]
        if not isinstance(sql, str) or not sql.strip() or ')havoc"' in sql:
            raise ValueError(
                f"{filename}: invalid SQL or raw-string delimiter collision"
            )
    return sorted(variants, key=lambda variant: variant["id"])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path)
    parser.add_argument("--check", action="store_true", help="check without writing")
    args = parser.parse_args()
    with ThreadPoolExecutor(max_workers=4) as executor:
        queries = list(
            executor.map(
                lambda number: read_query(number, args.source_dir), range(1, 23)
            )
        )
    parts = [
        "// Generated by scripts/import_tpch_havoc.py; do not edit.\n",
        "// Copyright (c) 2026 Joe Harris / BenchBox Project.\n",
        "// MIT License; see LICENSE in this directory.\n",
        f"// BenchBox revision: {REVISION}\n",
        "// clang-format off\n",
    ]
    for number, variants in enumerate(queries, 1):
        for variant in variants:
            query_id = f"Q{number:02}_V{variant['id']:02}"
            description = json.dumps(variant["description"], ensure_ascii=True)
            parts.append(
                f'\nHAVOC_QUERY("{query_id}", {description}, R"havoc('
                + variant["sql"]
                + ')havoc")\n'
            )
    parts.append("// clang-format on\n")
    generated = "".join(parts)
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("TPC-Havoc inventory differs; regenerate it")
        print("TPC-Havoc inventory matches all 220 upstream query labels")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"Imported 220 query labels into {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
